import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import FirebaseContextProvider from "./Context";

import { Toaster } from "@/app/Components/ui/sonner";

const geistSans = Geist({
  variable: "--font-Poppins",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-Poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <FirebaseContextProvider>{children}</FirebaseContextProvider>
        <Toaster
          position="top-center"
          expand={false}
          richColors
          toastOptions={{
            unstyled: true,
            classNames: {
              toast:
                "bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-4 rounded-xl shadow-lg flex items-center gap-3 w-full",
              title: "text-sm font-semibold text-zinc-900 dark:text-zinc-100",
              description: "text-xs text-zinc-500 dark:text-zinc-400",
            },
          }}
        />
      </body>
    </html>
  );
}
